- name: "install vim"
  apt: pkg={{ item }} force=yes update_cache=yes
  with_items:
    - vim
  sudo: yes
- name: "download dotfiles"
  git: repo=https://github.com/canpok1/dotfiles.git dest=/home/vagrant/dotfiles
  sudo: yes
  sudo_user: vagrant
- name: "setup dotfiles"
  shell: sh ./setup.sh chdir=/home/vagrant/dotfiles
  sudo: yes
  sudo_user: vagrant
